
spring:
  data:
    mongodb:
      uri: mongodb+srv://aakash_dutt_mathur:aakash2301@cluster0.wltqj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal